spring:
  application:
    name: ip-geolocation-service

server:
  port: 8080

app:
  geolocation:
    provider: ip-api
    api-url: http://ip-api.com/json
    timeout-seconds: 5
  fallback:
    country:
      code: BR
      name: Brazil
  cache:
    ttl-hours: 24
    max-size: 10000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true